-- Saloon Jukebox library seed. Generated by scripts/generate.mjs.
-- Audio: Kevin MacLeod (incompetech.com), CC BY 4.0. See MUSIC_LICENSES.md.
-- Safe to re-run: rows match on a deterministic id.

insert into public.songs (id, title, artist, album, genre, duration, audio_url, cover_url)
values
  ('f5b58826-afb4-5124-b3bc-b602fd42ed8a', 'Whiskey on the Mississippi', 'Kevin MacLeod', 'Funk and Blues', 'Blues', 195, 'music/whiskey-on-the-mississippi.mp3', 'covers/whiskey-on-the-mississippi.svg'),
  ('e2632909-b152-575f-8561-cc1b5c9f4df7', 'Fig Leaf Rag', 'Kevin MacLeod', 'Famous Classics', 'Ragtime', 209, 'music/fig-leaf-rag.mp3', 'covers/fig-leaf-rag.svg'),
  ('3c184c0c-3b5f-569e-8048-caefd1cfb4f0', 'Olde Timey', 'Kevin MacLeod', 'Silent Film - Bright', 'Ragtime', 195, 'music/olde-timey.mp3', 'covers/olde-timey.svg'),
  ('2a202d6f-9d44-58e5-bbb3-37ffd1bebc7f', 'Barroom Ballet', 'Kevin MacLeod', 'Silent Film - Bright', 'Ragtime', 57, 'music/barroom-ballet.mp3', 'covers/barroom-ballet.svg'),
  ('bef0f465-504e-5e7d-97c5-4ff7ba1767ba', 'Hillbilly Swing', 'Kevin MacLeod', 'Celtic and Folk', 'Bluegrass', 167, 'music/hillbilly-swing.mp3', 'covers/hillbilly-swing.svg'),
  ('d47175e7-d9a9-519f-ba26-42fa277e9000', 'Drankin Song', 'Kevin MacLeod', NULL, 'Folk', 246, 'music/drankin-song.mp3', 'covers/drankin-song.svg'),
  ('670b1a18-ede1-5848-9027-3c5970070f21', 'Guts and Bourbon', 'Kevin MacLeod', NULL, 'Country Rock', 209, 'music/guts-and-bourbon.mp3', 'covers/guts-and-bourbon.svg'),
  ('d676319d-c6be-575d-a8ef-e9d4b321ff23', 'Matt''s Blues', 'Kevin MacLeod', 'Funk and Blues', 'Blues', 167, 'music/matt-s-blues.mp3', 'covers/matt-s-blues.svg'),
  ('8347d452-c41c-5867-8e9c-c73e95a88cdf', 'Southern Gothic', 'Kevin MacLeod', 'Celtic and Folk', 'Southern Gothic', 147, 'music/southern-gothic.mp3', 'covers/southern-gothic.svg'),
  ('040397be-85c8-5100-9834-d84190cdfbda', 'DarxieLand', 'Kevin MacLeod', NULL, 'Dixieland', 146, 'music/darxieland.mp3', 'covers/darxieland.svg'),
  ('82bb5297-fb50-53ea-a315-8832e01dd114', 'Lost Frontier', 'Kevin MacLeod', 'Mystery', 'Western', 265, 'music/lost-frontier.mp3', 'covers/lost-frontier.svg'),
  ('4aa2bb83-7991-57e4-9b8d-c06c8f5e5cf5', 'Neo Western', 'Kevin MacLeod', 'Darkness and Unease', 'Western', 146, 'music/neo-western.mp3', 'covers/neo-western.svg'),
  ('049373a9-a887-5615-9efc-0ba1c5e4787b', 'River Valley Breakdown', 'Kevin MacLeod', NULL, 'Bluegrass', 369, 'music/river-valley-breakdown.mp3', 'covers/river-valley-breakdown.svg'),
  ('b8ab3a51-9d7e-5a1e-bb70-9dd006d12fe4', 'Cattails', 'Kevin MacLeod', 'Light', 'Folk', 159, 'music/cattails.mp3', 'covers/cattails.svg'),
  ('30b5912e-1530-5630-9009-ddb0a94fbe58', 'Still Pickin', 'Kevin MacLeod', 'Celtic and Folk', 'Bluegrass', 298, 'music/still-pickin.mp3', 'covers/still-pickin.svg'),
  ('929a7098-c073-59f5-8bc6-5efad7efa1a6', 'Fiddles McGinty', 'Kevin MacLeod', 'Celtic and Folk', 'Celtic', 207, 'music/fiddles-mcginty.mp3', 'covers/fiddles-mcginty.svg')
on conflict (id) do update set
  title = excluded.title, artist = excluded.artist, album = excluded.album,
  genre = excluded.genre, duration = excluded.duration,
  audio_url = excluded.audio_url, cover_url = excluded.cover_url;
