/**
 * Builds every derived artefact for the music library from one source of truth
 * (`scripts/library.source.json`, taken from Incompetech's public catalogue):
 *
 *   src/data/songs.json     library shipped with the app + local-mode fallback
 *   supabase/seed.sql       idempotent seed for the Supabase `songs` table
 *   MUSIC_LICENSES.md       per-track attribution, as CC BY 4.0 requires
 *
 * Durations are probed from the encoded files when ffprobe is available, so the
 * shared clock uses the real length rather than the catalogue's rounded value.
 *
 *   node scripts/build-library.mjs
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(readFileSync(resolve(root, 'scripts/library.source.json'), 'utf8'));

/** Stable UUIDv5-style id so seeds, re-runs and local mode always agree. */
const NAMESPACE = '9f1b7c4e-3a2d-4b6f-8e10-5c7a2d9b4e30';
function uuidFor(slug) {
  const hash = createHash('sha1')
    .update(Buffer.from(NAMESPACE.replace(/-/g, ''), 'hex'))
    .update(slug)
    .digest();
  const b = Buffer.from(hash.subarray(0, 16));
  b[6] = (b[6] & 0x0f) | 0x50; // version 5
  b[8] = (b[8] & 0x3f) | 0x80; // RFC 4122 variant
  const h = b.toString('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}

function probeDuration(file) {
  try {
    const out = execFileSync(
      'ffprobe',
      ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file],
      { encoding: 'utf8' },
    );
    const seconds = Math.round(Number(out.trim()));
    return Number.isFinite(seconds) && seconds > 0 ? seconds : null;
  } catch {
    return null; // ffprobe missing — fall back to the catalogue length.
  }
}

const sqlStr = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);

/**
 * Incompetech's own genre field is coarse ("Unclassifiable", "World", "Silent
 * Film Score"), which makes for poor browsing and poor search. These labels
 * describe what each track actually sounds like, based on the instrumentation
 * and "feel" recorded in the catalogue. Source metadata itself is untouched —
 * the real collection name is still carried through as the album.
 */
const GENRE = {
  'whiskey-on-the-mississippi': 'Blues',
  'fig-leaf-rag': 'Ragtime',
  'olde-timey': 'Ragtime',
  'barroom-ballet': 'Ragtime',
  'hillbilly-swing': 'Bluegrass',
  'drankin-song': 'Folk',
  'guts-and-bourbon': 'Country Rock',
  'matt-s-blues': 'Blues',
  'southern-gothic': 'Southern Gothic',
  darxieland: 'Dixieland',
  'lost-frontier': 'Western',
  'neo-western': 'Western',
  'river-valley-breakdown': 'Bluegrass',
  cattails: 'Folk',
  'still-pickin': 'Bluegrass',
  'fiddles-mcginty': 'Celtic',
};

const songs = source.map((t) => {
  const audioFile = resolve(root, 'public/music', `${t.slug}.mp3`);
  const probed = existsSync(audioFile) ? probeDuration(audioFile) : null;
  if (!existsSync(audioFile)) {
    console.warn(`  ! missing audio: public/music/${t.slug}.mp3`);
  }
  // "Misc"/"Unclassifiable"/"not in a collection" aren't real album names.
  // The album column is nullable, so leave it empty rather than show noise.
  const album = /not in a collection|^misc$|^unclassifiable$/i.test(t.album ?? '') ? null : t.album;

  return {
    id: uuidFor(t.slug),
    slug: t.slug,
    title: t.title,
    artist: t.artist,
    album,
    genre: GENRE[t.slug] ?? t.genre ?? null,
    duration: probed ?? t.duration,
    audio_url: `music/${t.slug}.mp3`,
    cover_url: `covers/${t.slug}.svg`,
    created_at: '2024-01-01T00:00:00.000Z',
  };
});

writeFileSync(resolve(root, 'src/data/songs.json'), `${JSON.stringify(songs, null, 2)}\n`);

// --- supabase/seed.sql ----------------------------------------------------
const seed = `-- Saloon Jukebox — library seed.
-- Generated by scripts/build-library.mjs. Do not edit by hand.
--
-- Safe to run repeatedly: rows are matched on their deterministic id, so
-- re-running updates metadata instead of creating duplicates.
--
-- Audio: Kevin MacLeod (incompetech.com), Creative Commons Attribution 4.0.
-- Attribution for every track is in MUSIC_LICENSES.md.

insert into public.songs (id, title, artist, album, genre, duration, audio_url, cover_url)
values
${songs
  .map(
    (s) =>
      `  (${sqlStr(s.id)}, ${sqlStr(s.title)}, ${sqlStr(s.artist)}, ${sqlStr(s.album)}, ${sqlStr(
        s.genre,
      )}, ${s.duration}, ${sqlStr(s.audio_url)}, ${sqlStr(s.cover_url)})`,
  )
  .join(',\n')}
on conflict (id) do update set
  title      = excluded.title,
  artist     = excluded.artist,
  album      = excluded.album,
  genre      = excluded.genre,
  duration   = excluded.duration,
  audio_url  = excluded.audio_url,
  cover_url  = excluded.cover_url;
`;
writeFileSync(resolve(root, 'supabase/seed.sql'), seed);

// --- MUSIC_LICENSES.md ----------------------------------------------------
const total = songs.reduce((n, s) => n + (s.duration ?? 0), 0);
const licenses = `# Music Licenses

Every audio file in \`public/music/\` is listed here with its source, licence and
attribution. Nothing in this repository is redistributed without a licence that
permits redistribution.

> **"Free to listen to" is not the same as "free to redistribute."**
> Only add tracks whose licence explicitly allows hosting and redistribution.
> See [Adding your own music](#adding-your-own-music).

## Summary

| | |
|---|---|
| Tracks | ${songs.length} |
| Total running time | ${Math.floor(total / 60)} min ${total % 60} s |
| Composer / performer | Kevin MacLeod |
| Source | [incompetech.com](https://incompetech.com/music/royalty-free/music.html) |
| License | [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) |
| Redistribution | Permitted, with attribution |
| Modification | Permitted (files were re-encoded to 128 kbps MP3 for web delivery) |

## Required attribution

CC BY 4.0 requires credit. This project satisfies it in three places: this file,
the "Music" section of the [README](README.md), and the in-app credit line shown
under the library. If you fork this project, keep the attribution.

The blanket credit for the whole library:

\`\`\`text
Music by Kevin MacLeod (incompetech.com)
Licensed under Creative Commons: By Attribution 4.0 License
https://creativecommons.org/licenses/by/4.0/
\`\`\`

## Tracks

${songs
  .map((s, i) => {
    const src = source[i];
    return `### ${i + 1}. ${s.title}

| Field | Value |
|---|---|
| **Track** | ${s.title} |
| **Artist** | ${s.artist} |
| **Album / collection** | ${s.album ?? '—'} |
| **Duration** | ${Math.floor((s.duration ?? 0) / 60)}:${String((s.duration ?? 0) % 60).padStart(2, '0')} |
| **Source** | Incompetech (the composer's own site) |
| **License** | CC BY 4.0 |
| **Attribution required** | Yes — "${s.title} by Kevin MacLeod \\| Licensed under Creative Commons: By Attribution 4.0" |
| **URL** | ${src.source_url} |
| **ISRC** | ${src.isrc ?? '—'} |
| **Local file** | \`public/music/${s.slug}.mp3\` |
`;
  })
  .join('\n')}
## Cover artwork

The album artwork in \`public/covers/\` is **not** third-party art. It is
generated from scratch by \`scripts/generate-covers.mjs\` and is covered by this
repository's own [MIT license](LICENSE) — there is no external image licence to
honour.

## Adding your own music

1. Drop the audio in \`public/music/\`.
2. Add an entry to \`scripts/library.source.json\`.
3. Run \`npm run build:library\` then \`npm run build:covers\`.
4. Apply \`supabase/seed.sql\` to your project.
5. **Record the licence here.** If you can't name a licence that allows
   redistribution, don't add the track.

Good sources of genuinely redistributable audio:

- [Incompetech](https://incompetech.com/music/royalty-free/music.html) — CC BY 4.0
- [Free Music Archive](https://freemusicarchive.org/) — check each track's licence
- [Musopen](https://musopen.org/) — public-domain classical recordings
- [ccMixter](http://ccmixter.org/) — Creative Commons remixes
- Your own recordings

Do **not** source audio from Spotify, Apple Music, or YouTube rips. Those are
neither licensed for redistribution nor permitted by this project.
`;
writeFileSync(resolve(root, 'MUSIC_LICENSES.md'), licenses);

console.log(`Wrote src/data/songs.json, supabase/seed.sql, MUSIC_LICENSES.md (${songs.length} tracks).`);
